### PR TITLE
Hooked up book backend to express app (finally)

### PR DESCRIPTION
**Pull request by sunnyxu2**
* New "Advanced" book router for adding, borrowing, returning, searching, and updating
* Changed old BookModel to make a Book2 model to prevent conflicts
* BookController bug fixes

### CODE REVIEW

**Review by arrennbaral — APPROVED** [review]
The implementation looks great.

**Comment by faribaasadi** [comment]
looks good

**Comment by roya120** [comment]
It works and looks good.

**Review by prazes — APPROVED** [review]
the backend connections  looks good

**Pull request merged**
